# Generated by Django 3.2 on 2024-01-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('fname', models.CharField(max_length=100, null=True)),
                ('cnic', models.IntegerField(max_length=100, null=True)),
                ('serial', models.IntegerField(max_length=100, null=True)),
                ('fno', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
